load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "move",
    hdrs = [
        "entity.h",
    ],
    srcs = [
        "entity.cpp",
    ],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)