cc_test(
    name = "move-test",
    size = "small",
    srcs = ["entity_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//Bjarne/cpp4/ch17/poc1/main:move",
    ],
)