load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "greet",
    hdrs = [
        "greet.h",
    ],
    srcs = [
        "greet.cpp",
    ],
    copts = ["-std=c++20"],
    visibility = ["//visibility:public"],
)