cc_test(
    name = "greet",
    size = "small",
    srcs = ["greet_test.cpp"],
    copts = ["-std=c++20"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//Bjarne/prog2/ch03/main:greet",
    ],
)